### PR TITLE
Fix to avoid creating empty Failed Test Log

### PR DESCRIPTION
**Pull request by kuznetsovmoci**

### CODE REVIEW

**Comment by mitza-oci** [comment]
Is this going to change what's written to `index.html`?

**Review by simpsont-oci — APPROVED** [review]

**Comment by jwillemsen** [comment]
Looks the scoreboard generation is broken, see for example http://scoreboard.ociweb.com/dds_doc_ace6tao2_ant_linux-rpi_gcc_d0o1/index.html, information is missing and the links that are there point to empty pages

**Comment by mitza-oci** [comment]
> 
> 
> Looks the scoreboard generation is broken, see for example http://scoreboard.ociweb.com/dds_doc_ace6tao2_ant_linux-rpi_gcc_d0o1/index.html, information is missing and the links that are there point to empty pages

Yes, we'll look into it.

**Comment by jwillemsen** [comment]
@mitza-oci Looks the index.html is still broken for the OpenDDS builds

**Comment by mitza-oci** [comment]
> 
> 
> @mitza-oci Looks the index.html is still broken for the OpenDDS builds

We are actively working on it

**Pull request merged**
